# Generated by Django 4.2.9 on 2024-01-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_interest_userprofile_show_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=50),
        ),
    ]
